name: Node.js CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 10.x ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: 'npm'
                    cache-dependency-path: mortgage-calculator-client/package-lock.json
            -   run: npm ci
                working-directory: mortgage-calculator-client
            -   run: npm run build --if-present
                working-directory: mortgage-calculator-client
            -   run: npm test
                working-directory: mortgage-calculator-client
